spring.datasource.url=jdbc:mysql://localhost:3306/consultant_management
spring.datasource.username=root
spring.datasource.password=MySQLTest123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false